### ISSUE TITLE
error getting annotations

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/vandam-daylong-demo#3]
I did:

```
source ~/ChildProjectVenv/bin/activate
datalad install https://github.com/LAAC-LSCP/vandam-daylong-demo.git
cd vandam-daylong-demo
datalad get annotations
```

and everything went well except for the last step, which yielded:

> [ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/converted/BN32_010007_0_0.csv)] 
get(error): annotations/cha/converted/BN32_010007_0_0.csv (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/raw/BN32_010007.cha)] 
get(error): annotations/cha/raw/BN32_010007.cha (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/converted/BN32_010007_0_0.csv)] 
get(error): annotations/its/converted/BN32_010007_0_0.csv (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/raw/BN32_010007.its)] 
get(error): annotations/its/raw/BN32_010007.its (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/converted/BN32_010007_0_0.csv)] 
get(error): annotations/vtc/converted/BN32_010007_0_0.csv (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/raw/BN32_010007.rttm)] 
get(error): annotations/vtc/raw/BN32_010007.rttm (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
[WARNING] could not get some content in /Users/acristia/Documents/git-data/vandam-daylong-demo/annotations ['/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/raw/BN32_010007.cha', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/raw/BN32_010007.its', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/raw/BN32_010007.rttm'] [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations)] 
get(impossible): annotations (directory) [could not get some content in /Users/acristia/Documents/git-data/vandam-daylong-demo/annotations ['/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/raw/BN32_010007.cha', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/its/raw/BN32_010007.its', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/converted/BN32_010007_0_0.csv', '/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/vtc/raw/BN32_010007.rttm']]
action summary:
  get (error: 6, impossible: 1)

To troubleshoot, I first checked that my installation of git-annex was appropriate:

```
brew install git-annex
```

Which led me to

```
brew upgrade git-annex
```
(I do see `Error: Permission denied @ apply2files - /usr/local/lib/docker/cli-plugins`, but this seems unrelated, so ignoring that.)

I then tried again `datalad get annotations`, but with the same outcome as before.

It's possible that something in our moving around datasets caused data to be unavailable from this source, since the error is: `[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/Users/acristia/Documents/git-data/vandam-daylong-demo/annotations/cha/converted/BN32_010007_0_0.csv)]`

**Comment by lucasgautheron** [comment]
Most often this happens when `datalad-osf` was not installed as the dataset was cloned.
Make sure datalad-osf is installed (pip install datalad-osf) and then do `git annex enableremote osf-annex-storage`

**Comment by alecristia** [comment]
that fixed it! for the record, my output:

> $ pip install datalad-osf
Collecting datalad-osf
  Downloading https://files.pythonhosted.org/packages/10/37/4f5ba979a5741f60af9babcb36bc115b2ed58885fbf5e3c1274deb314a68/datalad_osf-0.2.3.1-py2.py3-none-any.whl
Requirement already satisfied: annexremote>=1.4.0 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad-osf) (1.4.3)
Requirement already satisfied: datalad>=0.13.0 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad-osf) (0.14.0)
Collecting osfclient>=0.0.5 (from datalad-osf)
  Downloading https://files.pythonhosted.org/packages/a8/7a/8d6fe30d424329ced46a738faaea4150efb8eee656599b88a791cf7ad07e/osfclient-0.0.5-py2.py3-none-any.whl
Requirement already satisfied: future in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from annexremote>=1.4.0->datalad-osf) (0.18.2)
Requirement already satisfied: appdirs in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (1.4.4)
Requirement already satisfied: chardet>=3.0.4 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (3.0.4)
Requirement already satisfied: iso8601 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (0.1.13)
Requirement already satisfied: humanize in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (3.1.0)
Requirement already satisfied: fasteners>=0.14 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (0.15)
Requirement already satisfied: patool>=1.7 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (1.12)
Requirement already satisfied: tqdm in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (4.52.0)
Requirement already satisfied: wrapt in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (1.12.1)
Requirement already satisfied: boto in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (2.49.0)
Requirement already satisfied: keyring>=8.0 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (21.5.0)
Requirement already satisfied: keyrings.alt in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (4.0.1)
Requirement already satisfied: msgpack in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (1.0.0)
Requirement already satisfied: requests>=1.2 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (2.24.0)
Requirement already satisfied: jsmin in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (2.2.2)
Requirement already satisfied: PyGithub in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (1.53)
Requirement already satisfied: simplejson in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (3.17.2)
Requirement already satisfied: whoosh in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from datalad>=0.13.0->datalad-osf) (2.7.4)
Requirement already satisfied: six in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from osfclient>=0.0.5->datalad-osf) (1.15.0)
Requirement already satisfied: setuptools in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from humanize->datalad>=0.13.0->datalad-osf) (39.0.1)
Requirement already satisfied: monotonic>=0.1 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from fasteners>=0.14->datalad>=0.13.0->datalad-osf) (1.5)
Requirement already satisfied: importlib-metadata>=1; python_version < "3.8" in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from keyring>=8.0->datalad>=0.13.0->datalad-osf) (2.0.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from requests>=1.2->datalad>=0.13.0->datalad-osf) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from requests>=1.2->datalad>=0.13.0->datalad-osf) (2020.11.8)
Requirement already satisfied: idna<3,>=2.5 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from requests>=1.2->datalad>=0.13.0->datalad-osf) (2.10)
Requirement already satisfied: pyjwt in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from PyGithub->datalad>=0.13.0->datalad-osf) (1.7.1)
Requirement already satisfied: deprecated in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from PyGithub->datalad>=0.13.0->datalad-osf) (1.2.10)
Requirement already satisfied: zipp>=0.5 in /Users/acristia/ChildProjectVenv/lib/python3.6/site-packages (from importlib-metadata>=1; python_version < "3.8"->keyring>=8.0->datalad>=0.13.0->datalad-osf) (3.4.0)
Installing collected packages: osfclient, datalad-osf
Successfully installed datalad-osf-0.2.3.1 osfclient-0.0.5
You are using pip version 10.0.1, however version 21.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(ChildProjectVenv) (base) Mac-mini:vandam-daylong-demo acristia$ git annex enableremote osf-annex-storage
enableremote osf-annex-storage ok
(recording state in git...)
(ChildProjectVenv) (base) Mac-mini:vandam-daylong-demo acristia$ datalad get annotations
get(ok): annotations/cha/converted/BN32_010007_0_0.csv (file) [from osf-annex-storage...]                                                                               
get(ok): annotations/cha/raw/BN32_010007.cha (file) [from osf-annex-storage...]
get(ok): annotations/its/converted/BN32_010007_0_0.csv (file) [from osf-annex-storage...]
get(ok): annotations/its/raw/BN32_010007.its (file) [from osf-annex-storage...]
get(ok): annotations/vtc/converted/BN32_010007_0_0.csv (file) [from osf-annex-storage...]
get(ok): annotations/vtc/raw/BN32_010007.rttm (file) [from osf-annex-storage...]
get(ok): annotations (directory)
action summary:
  get (ok: 7)
